python main.py --config ./config/train/aagcn_B_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/aagcn_BM_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/aagcn_J_2d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/aagcn_J_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/aagcn_JM_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/ctrgcn_B_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/ctrgcn_BM_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/ctrgcn_J_2d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/ctrgcn_J_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/ctrgcn_JM_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/msg3d_B_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/msg3d_J_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/msg3d_JM_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/mstgcn_B_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/mstgcn_J_2d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/mstgcn_J_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/tdgcn_B_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/tdgcn_J_2d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/tdgcn_J_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/tegcn_B_3d.yaml --phase train --save-score True --device 0
python main.py --config ./config/train/tegcn_J_3d.yaml --phase train --save-score True --device 0