python main.py --config ./config/test/aagcn_B_3d.yaml --phase test --save-score True --weights ./output/aagcn_B_3d/runs-40-10240.pt --device 0 --result-path ../result/aagcn_B_3d_result.npy
python main.py --config ./config/test/aagcn_BM_3d.yaml --phase test --save-score True --weights ./output/aagcn_BM_3d/runs-36-9216.pt --device 0 --result-path ../result/aagcn_BM_3d_result.npy
python main.py --config ./config/test/aagcn_J_2d.yaml --phase test --save-score True --weights ./output/aagcn_J_2d/runs-38-9728.pt --device 0 --result-path ../result/aagcn_J_2d_reslut.npy
python main.py --config ./config/test/aagcn_J_3d.yaml --phase test --save-score True --weights ./output/aagcn_J_3d/runs-37-9472.pt --device 0 --result-path ../result/aagcn_J_3d_result.npy
python main.py --config ./config/test/aagcn_JM_3d.yaml --phase test --save-score True --weights ./output/aagcn_JM_3d/runs-37-9472.pt --device 0 --result-path ../result/aagcn_JM_3d_result.npy
python main.py --config ./config/test/ctrgcn_B_3d.yaml --phase test --save-score True --weights ./output/ctrgcn_B_3d/runs-61-15616.pt --device 0 --result-path ../result/ctrgcn_B_3d_result.npy
python main.py --config ./config/test/ctrgcn_BM_3d.yaml --phase test --save-score True --weights ./output/ctrgcn_BM_3d/runs-38-9728.pt --device 0 --result-path ../result/ctrgcn_BM_3d_reslut.npy
python main.py --config ./config/test/ctrgcn_J_2d.yaml --phase test --save-score True --weights ./output/ctrgcn_J_2d/runs-60-15360.pt --device 0 --result-path ../result/ctrgcn_J_2d_reslut.npy
python main.py --config ./config/test/ctrgcn_J_3d.yaml --phase test --save-score True --weights ./output/ctrgcn_J_3d/runs-37-9472.pt --device 0 --result-path ../result/ctrgcn_J_3d_reslut.npy
python main.py --config ./config/test/ctrgcn_JM_3d.yaml --phase test --save-score True --weights ./output/ctrgcn_JM_3d/runs-37-9472.pt --device 0 --result-path ../result/ctrgcn_JM_3d_result.npy
python main.py --config ./config/test/msg3d_B_3d.yaml --phase test --save-score True --weights ./output/msg3d_B_3d/runs-57-14592.pt --device 0 --result-path ../result/msg3d_B_3d_result.npy
python main.py --config ./config/test/msg3d_J_3d.yaml --phase test --save-score True --weights ./output/msg3d_J_3d/runs-48-12288.pt --device 0 --result-path ../result/msg3d_J_3d_result.npy
python main.py --config ./config/test/msg3d_JM_3d.yaml --phase test --save-score True --weights ./output/msg3d_JM_3d/runs-55-14080.pt --device 0 --result-path ../result/msg3d_JM_3d_result.npy
python main.py --config ./config/test/mstgcn_B_3d.yaml --phase test --save-score True --weights ./output/mstgcn_B_3d/runs-43-11008.pt --device 0 --result-path ../result/mstgcn_B_3d_result.npy
python main.py --config ./config/test/mstgcn_J_2d.yaml --phase test --save-score True --weights ./output/mstgcn_J_2d/runs-60-15360.pt --device 0 --result-path ../result/mstgcn_J_2d_result.npy
python main.py --config ./config/test/mstgcn_J_3d.yaml --phase test --save-score True --weights ./output/mstgcn_J_3d/runs-43-11008.pt --device 0 --result-path ../result/mstgcn_J_3d_result.npy
python main.py --config ./config/test/tdgcn_B_3d.yaml --phase test --save-score True --weights ./output/tdgcn_B_3d/runs-43-5504.pt --device 0 --result-path ../result/tdgcn_B_3d_result.npy
python main.py --config ./config/test/tdgcn_J_2d.yaml --phase test --save-score True --weights ./output/tdgcn_J_2d/runs-43-11008.pt --device 0 --result-path ../result/tdgcn_J_2d_result.npy
python main.py --config ./config/test/tdgcn_J_3d.yaml --phase test --save-score True --weights ./output/tdgcn_J_3d/runs-37-4736.pt --device 0 --result-path ../result/tdgcn_J_3d_result.npy
python main.py --config ./config/test/tegcn_B_3d.yaml --phase test --save-score True --weights ./output/tegcn_B_3d/runs-39-9984.pt --device 0 --result-path ../result/tegcn_B_3d_result.npy
python main.py --config ./config/test/tegcn_J_3d.yaml --phase test --save-score True --weights ./output/tegcn_J_3d/runs-39-9984.pt --device 0 --result-path ../result/tegcn_J_3d_result.npy