work_dir: ./output/aagcn_B_3d

# feeder
feeder: dataset.feeder.Feeder
train_feeder_args: 
  data_path: ../../Process_data/save_3d_pose/bone3d.npz
  data_split: train
  p_interval: [0.5, 1]
  window_size: 64
  bone: False
  vel: False

  # /MixFormerGcn/Process_data/save_3d_pose/bone3d_test.npz

test_feeder_args:
  data_path: ../../Process_data/save_3d_pose/bone3d.npz
  data_split: test
  p_interval: [0.95]
  window_size: 64
  bone: False
  vel: False

# model
model: model.aagcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0,1]
batch_size: 64
test_batch_size: 64
num_epoch: 42
nesterov: True
