x_train_path: "./data/train_bone_motion.npy"
y_train_path: "./data/train_label.npy"
x_valid_path: "./data/val_bone_motion.npy"
y_valid_path: "./data/val_label.npy"
x_test_path: "./data/test_bone_motion.npy"
y_test_path: "./data/test_label.npy"
save_name: "bonemotion3d"