x_train_path: "./data/train_joint.npy"
y_train_path: "./data/train_label.npy"
x_valid_path: "./data/val_joint.npy"
y_valid_path: "./data/val_label.npy"
x_test_path: "./data/test_joint.npy"
y_test_path: "./data/test_label.npy"
save_name: "joint3d"