x_train_path: "./data/combined_train.npy"
y_train_path: "./data/train_label.npy"
x_valid_path: "./data/combined_val.npy"
y_valid_path: "./data/val_label.npy"
x_test_path: "./data/combined_test.npy"
y_test_path: "./data/test_label.npy"
save_name: "combined.npz"